name: rns_app
description: RnsWeb organisation application.
publish_to: 'none'
version: 0.2.3+10

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.8
  get: ^4.6.5
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.0
  dropdown_button2: ^2.3.9
  flutter_slidable: ^3.0.1
  url_launcher: ^6.1.14
  firebase_messaging: ^14.7.10
  unique_identifier: ^0.3.0
  flutter_html_v3: ^3.0.6
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  open_file: ^3.3.2
  file_picker: ^6.1.1
  photo_manager: ^3.0.0-dev.5
  photo_manager_image_provider: ^2.1.0
  mime: ^1.0.4
  device_info_plus: ^9.1.1
  flutter_inappwebview: ^6.0.0
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/alt_icons/
    - assets/launch_icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 700
